# Generated by Django 2.2.3 on 2019-07-16 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20190711_1553'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
    ]
