# Generated by Django 2.2.3 on 2019-07-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='creator',
        ),
    ]
