# Generated by Django 2.2.3 on 2019-07-11 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190711_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='category.Category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
