# Generated by Django 2.2.3 on 2019-07-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20190711_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
