# Generated by Django 2.2.3 on 2019-07-11 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0004_auto_20190711_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cellphone', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('neighborhood', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client.Client')),
            ],
        ),
    ]
