# Generated by Django 2.2.3 on 2019-07-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaddress',
            name='zip_address',
            field=models.IntegerField(default=112222, max_length=15),
            preserve_default=False,
        ),
    ]
