# Generated by Django 2.2.3 on 2019-07-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_address', '0003_auto_20190712_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='details',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
