# Generated by Django 2.2.3 on 2019-07-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_address', '0004_auto_20190712_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
