# Generated by Django 2.2.3 on 2019-07-16 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_itens', '0002_auto_20190712_1155'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitens',
            table='order_itens',
        ),
    ]
